# Copyright (c) 2024, Academy of Intelligent Innovation, Shandong Universiy, China.P.R. All rights reserved.<BR>

EDK2_TEST_PARSER_VERSION=main

.PHONY: brs-edk2-test-parser
brs-edk2-test-parser:
	@echo "Building BRS EDK2-Test-Parser..."
	git clone -b $(EDK2_TEST_PARSER_VERSION) https://git.gitlab.arm.com/systemready/edk2-test-parser.git
